package com.sf.module.pcrs.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 飞行员收藏.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class MyPilot implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Integer id;

	/** user_id. */
	private Integer userId;

	/** pilot_id. */
	private Integer pilotId;

	/** 创建时间. */
	private Date createOn;

	/** 创建人. */
	private String createBy;

	/** 修改时间. */
	private Date modifyOn;

	/** 修改人. */
	private String modifyBy;

	/** 是否删除. */
	private Integer ifDel;

	/** 是否有效. */
	private Integer status;

	/**
	 * Constructor.
	 */
	public MyPilot() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the user_id.
	 * 
	 * @param userId
	 *            user_id
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * Get the user_id.
	 * 
	 * @return user_id
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * Set the pilot_id.
	 * 
	 * @param pilotId
	 *            pilot_id
	 */
	public void setPilotId(Integer pilotId) {
		this.pilotId = pilotId;
	}

	/**
	 * Get the pilot_id.
	 * 
	 * @return pilot_id
	 */
	public Integer getPilotId() {
		return this.pilotId;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createOn
	 *            创建时间
	 */
	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateOn() {
		return this.createOn;
	}

	/**
	 * Set the 创建人.
	 * 
	 * @param createBy
	 *            创建人
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * Get the 创建人.
	 * 
	 * @return 创建人
	 */
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * Set the 修改时间.
	 * 
	 * @param modifyOn
	 *            修改时间
	 */
	public void setModifyOn(Date modifyOn) {
		this.modifyOn = modifyOn;
	}

	/**
	 * Get the 修改时间.
	 * 
	 * @return 修改时间
	 */
	public Date getModifyOn() {
		return this.modifyOn;
	}

	/**
	 * Set the 修改人.
	 * 
	 * @param modifyBy
	 *            修改人
	 */
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	/**
	 * Get the 修改人.
	 * 
	 * @return 修改人
	 */
	public String getModifyBy() {
		return this.modifyBy;
	}

	/**
	 * Set the 是否删除.
	 * 
	 * @param ifDel
	 *            是否删除
	 */
	public void setIfDel(Integer ifDel) {
		this.ifDel = ifDel;
	}

	/**
	 * Get the 是否删除.
	 * 
	 * @return 是否删除
	 */
	public Integer getIfDel() {
		return this.ifDel;
	}

	/**
	 * Set the 是否有效.
	 * 
	 * @param status
	 *            是否有效
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * Get the 是否有效.
	 * 
	 * @return 是否有效
	 */
	public Integer getStatus() {
		return this.status;
	}


}
