package com.sf.module.pcrs.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 飞行员.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Pilot implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Integer id;

	/** 飞行员名称. */
	private String pilot;

	/** 执照. */
	private String licence;

	/** 公司id. */
	private Integer airlineId;

	/** 公司名称. */
	private String airline;
	
	/** 头像. */
	private String avatar;
	
	/** 性别. */
	private String sex;

	/** 创建时间. */
	private Date createOn;

	/** 创建人. */
	private String createBy;

	/** 修改时间. */
	private Date modifyOn;

	/** 修改人. */
	private String modifyBy;

	/** 是否删除. */
	private Integer ifDel;

	/** 是否有效. */
	private Integer status;

	/**
	 * Constructor.
	 */
	public Pilot() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the 飞行员名称.
	 * 
	 * @param pilot
	 *            飞行员名称
	 */
	public void setPilot(String pilot) {
		this.pilot = pilot;
	}

	/**
	 * Get the 飞行员名称.
	 * 
	 * @return 飞行员名称
	 */
	public String getPilot() {
		return this.pilot;
	}

	/**
	 * Set the 执照.
	 * 
	 * @param licence
	 *            执照
	 */
	public void setLicence(String licence) {
		this.licence = licence;
	}

	/**
	 * Get the 执照.
	 * 
	 * @return 执照
	 */
	public String getLicence() {
		return this.licence;
	}

	/**
	 * Set the 公司id.
	 * 
	 * @param airlineId
	 *            公司id
	 */
	public void setAirlineId(Integer airlineId) {
		this.airlineId = airlineId;
	}

	/**
	 * Get the 公司id.
	 * 
	 * @return 公司id
	 */
	public Integer getAirlineId() {
		return this.airlineId;
	}

	/**
	 * Set the 头像.
	 * 
	 * @param avatar
	 *            头像
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	/**
	 * Get the 头像.
	 * 
	 * @return 头像
	 */
	public String getAvatar() {
		return this.avatar;
	}

	/**
	 * Get the 性别.
	 * 
	 * @return 性别
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * Set the 性别.
	 * 
	 * @param sex
	 *            性别
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createOn
	 *            创建时间
	 */
	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateOn() {
		return this.createOn;
	}

	/**
	 * Set the 创建人.
	 * 
	 * @param createBy
	 *            创建人
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * Get the 创建人.
	 * 
	 * @return 创建人
	 */
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * Set the 修改时间.
	 * 
	 * @param modifyOn
	 *            修改时间
	 */
	public void setModifyOn(Date modifyOn) {
		this.modifyOn = modifyOn;
	}

	/**
	 * Get the 修改时间.
	 * 
	 * @return 修改时间
	 */
	public Date getModifyOn() {
		return this.modifyOn;
	}

	/**
	 * Set the 修改人.
	 * 
	 * @param modifyBy
	 *            修改人
	 */
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	/**
	 * Get the 修改人.
	 * 
	 * @return 修改人
	 */
	public String getModifyBy() {
		return this.modifyBy;
	}

	/**
	 * Set the 是否删除.
	 * 
	 * @param ifDel
	 *            是否删除
	 */
	public void setIfDel(Integer ifDel) {
		this.ifDel = ifDel;
	}

	/**
	 * Get the 是否删除.
	 * 
	 * @return 是否删除
	 */
	public Integer getIfDel() {
		return this.ifDel;
	}

	/**
	 * Set the 是否有效.
	 * 
	 * @param status
	 *            是否有效
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * Get the 是否有效.
	 * 
	 * @return 是否有效
	 */
	public Integer getStatus() {
		return this.status;
	}

	public String getAirline() {
		return airline;
	}

	public void setAirline(String airline) {
		this.airline = airline;
	}

}
