package com.sf.module.pcrs.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 飞行员考核表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CheckRecord implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Integer id;

	/** pilot_id. */
	private Integer pilotId;

	/** 登机时间. */
	private Date boardingTime;

	/** 考核内容. */
	private String checkContent;

	/** 评价状态(待评价、PASS、FAIL). */
	private Integer checkStatus;

	/** 考核图片. */
	private String checkImages;

	/** 考核员. */
	private String assessors;
	
	/** 机型. */
	private String acType;
	
	/** 飞行时间. */
	private int flightMinute;

	/** 创建时间. */
	private Date createOn;

	/** 创建人. */
	private String createBy;

	/** 修改时间. */
	private Date modifyOn;

	/** 修改人. */
	private String modifyBy;

	/** 是否删除. */
	private Integer ifDel;

	/** 是否有效. */
	private Integer status;

	/**
	 * Constructor.
	 */
	public CheckRecord() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the pilot_id.
	 * 
	 * @param pilotId
	 *            pilot_id
	 */
	public void setPilotId(Integer pilotId) {
		this.pilotId = pilotId;
	}

	/**
	 * Get the pilot_id.
	 * 
	 * @return pilot_id
	 */
	public Integer getPilotId() {
		return this.pilotId;
	}

	/**
	 * Set the 登机时间.
	 * 
	 * @param boardingTime
	 *            登机时间
	 */
	public void setBoardingTime(Date boardingTime) {
		this.boardingTime = boardingTime;
	}

	/**
	 * Get the 登机时间.
	 * 
	 * @return 登机时间
	 */
	public Date getBoardingTime() {
		return this.boardingTime;
	}

	/**
	 * Set the 考核内容.
	 * 
	 * @param checkContent
	 *            考核内容
	 */
	public void setCheckContent(String checkContent) {
		this.checkContent = checkContent;
	}

	/**
	 * Get the 考核内容.
	 * 
	 * @return 考核内容
	 */
	public String getCheckContent() {
		return this.checkContent;
	}

	/**
	 * Set the 评价状态(待评价、PASS、FAIL).
	 * 
	 * @param checkStatus
	 *            评价状态(待评价、PASS、FAIL)
	 */
	public void setCheckStatus(Integer checkStatus) {
		this.checkStatus = checkStatus;
	}

	/**
	 * Get the 评价状态(待评价、PASS、FAIL).
	 * 
	 * @return 评价状态(待评价、PASS、FAIL)
	 */
	public Integer getCheckStatus() {
		return this.checkStatus;
	}

	/**
	 * Set the 考核图片.
	 * 
	 * @param checkImages
	 *            考核图片
	 */
	public void setCheckImages(String checkImages) {
		this.checkImages = checkImages;
	}

	/**
	 * Get the 考核图片.
	 * 
	 * @return 考核图片
	 */
	public String getCheckImages() {
		return this.checkImages;
	}

	/**
	 * Set the 考核员.
	 * 
	 * @param assessors
	 *            考核员
	 */
	public void setAssessors(String assessors) {
		this.assessors = assessors;
	}

	/**
	 * Get the 考核员.
	 * 
	 * @return 考核员
	 */
	public String getAssessors() {
		return this.assessors;
	}

	/**
	 * Get the 机型.
	 * 
	 * @return 机型
	 */
	public String getAcType() {
		return acType;
	}

	/**
	 * Set the 机型.
	 * 
	 * @param acType
	 *            机型
	 */
	public void setAcType(String acType) {
		this.acType = acType;
	}

	/**
	 * Get the 飞行时间.
	 * 
	 * @return 飞行时间
	 */
	public int getFlightMinute() {
		return flightMinute;
	}

	/**
	 * Set the 飞行时间.
	 * 
	 * @param flightMinute
	 *            飞行时间
	 */
	public void setFlightMinute(int flightMinute) {
		this.flightMinute = flightMinute;
	}
	
	/**
	 * Set the 创建时间.
	 * 
	 * @param createOn
	 *            创建时间
	 */
	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateOn() {
		return this.createOn;
	}

	/**
	 * Set the 创建人.
	 * 
	 * @param createBy
	 *            创建人
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * Get the 创建人.
	 * 
	 * @return 创建人
	 */
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * Set the 修改时间.
	 * 
	 * @param modifyOn
	 *            修改时间
	 */
	public void setModifyOn(Date modifyOn) {
		this.modifyOn = modifyOn;
	}

	/**
	 * Get the 修改时间.
	 * 
	 * @return 修改时间
	 */
	public Date getModifyOn() {
		return this.modifyOn;
	}

	/**
	 * Set the 修改人.
	 * 
	 * @param modifyBy
	 *            修改人
	 */
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	/**
	 * Get the 修改人.
	 * 
	 * @return 修改人
	 */
	public String getModifyBy() {
		return this.modifyBy;
	}

	/**
	 * Set the 是否删除.
	 * 
	 * @param ifDel
	 *            是否删除
	 */
	public void setIfDel(Integer ifDel) {
		this.ifDel = ifDel;
	}

	/**
	 * Get the 是否删除.
	 * 
	 * @return 是否删除
	 */
	public Integer getIfDel() {
		return this.ifDel;
	}

	/**
	 * Set the 是否有效.
	 * 
	 * @param status
	 *            是否有效
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * Get the 是否有效.
	 * 
	 * @return 是否有效
	 */
	public Integer getStatus() {
		return this.status;
	}


}
